### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takuto95** [takuto95/furima-31488#9]
フリマアプリをherokuアップロードしましたので、ご確認お願いします。
URL:https://furima-31488.herokuapp.com/
Basic認証：ID admin / Pass 2222
出品者： ID aaa95@aaa / Pass test95
購入者： ID aaa@aaa / Pass test95
クレジット情報 番号 4242424242424242 / 有効期限 3 23 / CVC 123

**Comment by kana-create** [comment]
takuto95さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると遷移出来てしまう
・ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、遷移出来てしまう

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takuto95** [comment]
ご確認ありがとうございます。修正箇所を修正しましたので、再度ご確認お願いします。

**Comment by kana-create** [comment]
takuto95さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
